# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Qualys - Build, scan, push and upload sarif report

# on:
#   push:
#     branches: [ $default-branch, $protected-branches ]
#   pull_request:
#     branches: [ $default-branch ]
#   schedule:
#     - cron: $cron-weekly
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      # Tag image to be built
      # Change ${{ github.repository }} variable by another image name if you want but don't forget changing also image-tag below
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Get sha
      #imagehash=$(docker push repo/image:tag | grep sha | cut -d ' ' -f 3)
      run: export SHA256=$(docker images --no-trunc --quiet ${{ github.repository }}:latest)

    - name: Get digest
      #imagehash=$(docker push repo/image:tag | grep sha | cut -d ' ' -f 3)
      run: export DIGEST=$(echo $SHA256  | cut -c8-)

      

    - name: Tag docker  
      run: docker tag ${{ github.repository }}:latest qualys_scan_target:$DIGEST


    # reference : https://www.youtube.com/watch?v=dHuksXTLA2k

    - name: Qualys
      run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          # or
          "${{ format('{0}/.github/workflows/script.sh', github.workspace) }}"
      shell: bash

