# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Qualys - Build, scan, push and upload sarif report

# on:
#   push:
#     branches: [ $default-branch, $protected-branches ]
#   pull_request:
#     branches: [ $default-branch ]
#   schedule:
#     - cron: $cron-weekly
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Check file existence"
      uses: andstor/file-existence-action@v1
      with:
        files: "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

    - name: Install Qualys Daemon
      run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
      shell: bash
    - name: Build the Docker image
      # Tag image to be built
      # Change ${{ github.repository }} variable by another image name if you want but don't forget changing also image-tag below
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest

    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Get sha
      #imagehash=$(docker push repo/image:tag | grep sha | cut -d ' ' -f 3)
      run: export SHA256=$(docker images --no-trunc --quiet ${{ github.repository }}:latest)

    - name: Get digest
      #imagehash=$(docker push repo/image:tag | grep sha | cut -d ' ' -f 3)
      run: 
          export DIGEST=$(echo $SHA256  | cut -c8-)
          export TAG="qualys_scan_target:$DIGEST"

    - name: Tag docker  
      run:  
          echo "TAG= $TAG"
          docker tag ${{ github.repository }}:latest $TAG

    # reference : https://www.youtube.com/watch?v=dHuksXTLA2k
    - name: Docker PS
      run: 
          echo "::set-output name=author::$(sudo docker ps -a)"
    - name: "Check file existence"
      uses: andstor/file-existence-action@v1
      with:
        files: "/home/runner/work/qualys_github_helloworld/.github/workflows/qualysscript.sh"
    - name: Check the images
      env:
         QUALYS_USER: '${{ secrets.QUALYS_USER}}'
         QUALYS_PASSWORD: '${{ secrets.QUALYS_PASSWORD }}'
         QUALYS_URL : 'https://qualysguard.qg2.apps.qualys.com'
      run: |
          chmod +x "./qualysscript.sh"
          # run script echo "validateimage.sh <Qualys API Server> <Username> <Password> <Image Id|Name>"
          "./qualysscript.sh $QUALYS_URL $QUALYS_USER $QUALYS_PASSWORD $DIGEST "
      
      shell: bash

    - name: Sleep 
      env:
         QUALYS_USER: '${{ secrets.QUALYS_USER}}'
         QUALYS_PASSWORD: '${{ secrets.QUALYS_PASSWORD }}'
      run: |
        sleep 30  
      shell: bash
